#!/bin/sh

case "$(printf "lock\\nsuspend\\nhibernate\\nlogout\\nreboot\\nshutdown" | dmenu -i -nb '#24273a' -nf '#cad3f5' -sf '#181926' -sb '#b7bdf8' -fn 'JetBrainsMono nerd font:size=11' -p "⏻ ")" in
	lock) xscreensaver-command -lock ;;
	suspend) systemctl suspend ;;
	hibernate) systemctl hibernate ;;
	logout) bspc quit ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
