#!/bin/bash

# move to a new empty workspace
~/.bin/next-empty-workspace-bspwm.sh

# open codeforces contest page 
brave --new-window 'https://www.codeforces.com/contests' &

# open vscode in the cp folder
code ~/Programs/CP &
