#!/bin/bash

# move to a new empty workspace
~/.config/i3/scripts/empty_workspace

# open codechef 
brave --new-window 'https://www.codeforces.com/contests' &

# open vscode in the cp folder
code ~/Programs/CP &
