#! /bin/sh

# start sxhkd 
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a vlc desktop='^8' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Blueman-manager state=floating
bspc rule -a nm-connection-editor state=floating
bspc rule -a Yad state=floating
bspc rule -a lxappearance state=floating
bspc rule -a feh state=floating

#=============================================
#                   Border
#=============================================

bspc config focused_border_color        "#b7bdf8"
bspc config normal_border_color         "#6e738d"
bspc config active_border_color         "#cad3f5"


#=============================================
#                  Autostart                 
#=============================================

# start picom compositor
picom --config  ~/.config/picom/picom.conf &

#get auth work with polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# set wallpaper
~/.config/.fehbg &

# set powersavings for display:
xset s 480 dpms 600 600 600 &

# Desktop notifications
dbus-launch dunst --config ~/.config/dunst/dunstrc &

# launch tray applets
killall nm-applet
nm-applet &

killall blueman-applet
blueman-applet &

# start libinput-gestures
libinput-gestures-setup start &

# polybar
killall polybar
~/.config/polybar/launch.sh &

# start greenclip daemon
greenclip daemon &

# start low battery notifier script
killall low_bat_notifier.sh
~/.bin/low_bat_notifier.sh &

